### ISSUE TITLE
WIP - What or How are the RuleID's defined?

### ISSUE THREAD

**Issue by Absoblogginlutely** [MicrosoftDocs/OfficeDocs-o365seccomp#409]
When a sample X-Microsoft-Antispam has a weird RuleID listed (shown below), how do we know what rule that refers to?
	BCL:6;PCL:0;RULEID:(2390118)(7020095)(4652040)(5600110)(711020)(4605104)(1401299)(8001031)(1421009)(1405096)(71702078);SRVR:BY1PR13MB0246;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b0c22e-ec20-d8dc-bbc5-cfbb9e98350e
* Version Independent ID: d9a1bac2-69ef-5fa7-23f1-417d7454c4cc
* Content: [Anti-spam message headers](https://docs.microsoft.com/en-us/office365/securitycompliance/anti-spam-message-headers)
* Content Source: [SecurityCompliance/anti-spam-message-headers.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-spam-message-headers.md)
* Service: **o365-seccomp**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
Hello @Absoblogginlutely! Thank you for raising this question. We are looking into this, and we'll post an update here soon.

**Comment by onspring-technologies** [comment]
If you could publish all the rules, that would be great. There are tons of SpamAssassin tools out there that help us be better, and are open for the world to see. Even just describing the issue with each code would be great. 

We're getting a -2.4 spamassassin score, but somehow Outlook.com is flagigng our email as spam, even with valid DKIM, SPF and DMARC, and all the other wonderful goodies you can do to improve standing (like reverse IP lookups, etc)

BCL:0;PCL:0;RULEID:(2390118)(5000110)(711020)(4605104)(610169)(650170)(651021)(8291501071);

**Comment by beuss** [comment]
Same here, mails are classified as junk without any feedback despite DMARC/DKIM being properly configured. We've got a bunch of ruleid without any mean to determine why mail is junked.
SNDS doesn't help, JMRP neither and support has nothing to say except standard recommendation about bulk mail (hint: we don't do mailings…)

**Comment by lion988** [comment]
Please,

Where can I check the rules that antispam is detecting.

Phishing messages are being delivered to the inbox

BCL:0;PCL:0;RULEID:(2390118)(7020095)(4652040)(5600127)(711020)(4605104)(1401299)(1421009)(71702078);SRVR:CP2P15201MB2067;

**Comment by ianc911** [comment]
Same issue here. We have a third party mailing registration and application messages for us that are getting quarantined even through SPF and DKIM are passing. It is ridiculous that MS does not provide a method to reliably determine the reason for classifying the message as spam. How can this issue be addressed without reliable and accurate diagnostic info?

**Comment by MatthewDVance** [comment]
We're getting bounces right from Outlook through O365, not even 3rd party mailing system.
NEED TO KNOW what these mean.

**Comment by denisebmsft** [comment]
Thanks, everyone, for the feedback! We are looking into this.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by MatthewDVance** [comment]
RULEID:(2390118)(7020095)(4652040)(7021145)(8989299)(5600140)(711020)(4605104)(4534185)(7022145)(4603075)(4627221)(201702281549075)(8990200)(7048125)(7024125)(7027125)(7023125)(2017052603328)(49563074)(7193020);  

This from Bounced email YESTERDAY that happened in the middle of back-and-forth conversation via Email...  Fun fun fun.

**Comment by araker** [comment]
+1 I have the same issue. Mail sent to spam, but can't figure out why. A detailed explanation of the rules would be very helpful.

**Comment by ianc911** [comment]
"Thanks, everyone, for the feedback! We are looking into this"

What did you find when you looked into it?

**Comment by MatthewDVance** [comment]
I'm sorry. But you made my day. LOL.

**Comment by Andy9999** [comment]
In b4 thread is closed as resolved. :)

Here is ours, already pasted it in the closed NV:NLI thread (what ever the reason was to close it):
X-Microsoft-Antispam: BCL:5;PCL:0;RULEID:(2390118)(5000113)(711020)(4605104)(610169)(650170)(8291501072);SRVR:SN1NAM04HT077;

From MS documention for BCL:
...
4, 5, 6, 7 | The message is from a bulk sender that generates a mixed number of complaints.
-- | --

I checked in Microsoft's SDNS and JMRP and there the IP has normal status. We never received any complaint through JMRP. Additionally we never, ever sent or will send out any spam. All our customers have to do, when placing an order, is to register an account with us that requires email verification.

The word generates implies that there is complaints, which is at best a blatant lie. Some say that BCL7 is needed to be sorted out though. Is that true or not so true? Is it one of the "rules"?

**Comment by Andy9999** [comment]
Our BCL problem has been solved and it is zero again after contacting MS here:
https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75

And there (I think this one is only needed if the IP is black listed which wasn't the case for us):
https://sender.office.com/

Also it seems mail gets delivered again. I hope it stays like this.

**Comment by MatthewDVance** [comment]
BCL:4;PCL:0;RULEID:(2390118)(7020095)(4652040)(5600148)(711020)(4605104)(8001031)(1405096)(71702078)

Still ongoing issue.  This time, another client with their OWN email campaigns going to junk (both ConstantContact and MailChimp).  still no update on what these ruleIDs are, and we're now 4 months later, still unable to help our clients efficiently.

**Comment by patschi** [comment]
My mails also are thrown into Junk for a few weeks, for unclear reasons. This happened in an ongoing mail conversation in both directions with a company hosting on O365. I'm not able to find any reason what goes wrong - using SPF, DKIM, DMARC, ARC, Microsoft's SNDS and JMRP program and all are in a good state. Furthermore the mailserver IP is neither blacklisted at Microsoft nor listed on any blacklist at all.

It'd really help to be able to understand what all these magic rules means. Beside that, only MS/O365 are making troubles regarding mail delivery.

**Comment by andryyy** [comment]
Outlook spam filtering is so fucked up, we move away customers from O365 as they fail to receive important mail from legit senders. Well done, Microsoft.

**Comment by TokyoScarab** [comment]
Hi @Absoblogginlutely and thank you for raising this issue!  I will be looking more into this issue.  There are some things I would like to add that I didn't see mentioned in this discussion.  The RULEID section returns with the ID number of the rule that was used to handle that message.  These ID numbers are defined upon the creation of that policy in your particular system.  Finding what policies these IDs actually pertain to is usually limited to the authorization level of a particular user.  Though, with the proper access, you should be able to look up the mail flow rules of these messages with PowerShell using the [Get-TransportRule](https://docs.microsoft.com/powershell/module/exchange/policy-and-compliance/get-transportrule?view=exchange-ps).  I'm not sure if this answers all of your specific questions, but it should shed some light on this question.  If you have more comments or questions on this, feel free to comment them below.

**Comment by MatthewDVance** [comment]
>  These ID numbers are defined upon the creation of that policy in your particular system. Finding what policies these IDs actually pertain to is usually limited to the authorization level of a particular user. 

there's a lot more ruleID's than I have policies.... soo.... 

But thanks for that tidbit of info.  at least we can go RTFM on our own systems now.

**Comment by TokyoScarab** [comment]
@MatthewDVance  Let me clarify that a little bit.  The RULEID that shows up in the header cannot be cross-referenced with the ID of the rule that flagged it.  A couple ways to address this would be to [Run A Message Trace](https://docs.microsoft.com/exchange/monitoring/trace-an-email-message/run-a-message-trace-and-view-results) or have the rule include a header that gives more information as explained [here](https://blogs.technet.microsoft.com/eopfieldnotes/2014/11/20/easily-tell-which-transport-rules-a-message-triggered/).  The second one obviously only helps if you that kind of access in your organization, but I included it because it can be helpful to know.

**Comment by patschi** [comment]
Sorry @TokyoScarab, but I'm honestly not sure how this should help regarding the question asked here. I'm having a state-of-the-art linux-based mailserver and all mails sent over to Office365/Outlook just started being flagged as junk.

Just to note that this happened in the middle (!) of an ongoing, legit and important mail conversation in both directions (!). The junk-thing caused troubles and confusion on both sides for a while. I had to use LinkedIn to make them aware that the mails might be in junk or whereever.

The headers are added by systems over at Microsoft, where noone knows what they are actually meaning or having any clue to make the buggy spam filters at Microsoft a bit more happier. I'd really like that customers, friends or other important recipients does get my mails delivered just like at all other mail providers. I'm not the only one affected by this.

**Comment by TokyoScarab** [comment]
@MSFTTracyP Being the author for this set of documentation, I would love your insight on this discussion.

**Comment by 0-SamboNZ-0** [comment]
If I understand correctly, what @TokyoScarab is saying is that the RULEID is arbitrary, ie; the IDs are different for each installation.  Therefore there is no 'one size fits all' interpretation for RULEIDs.

However, assuming the RULEIDs are consistent across Microsoft's spam filter farm servers, they could technically publish them, assuming they were willing to do so of course.

In any case, the issue still stands and I have the same problem, so solutions from MS would be appreciated!

**Comment by MatthewDVance** [comment]
@YokyoScarab Thanks. That's good BP that nobody knows yet.
Problem is, I don't have any transport rules set!  yet the RULEID list is a mile long.

**Comment by beuss** [comment]
If MS doesn't want to publish its RULEID matching, at least, stop dropping human written, SPF valid, DKIM signed messages, and fire monkeys running support trained to paste the same answer to every complaint (« add an un subscribe link »… IT'S NOT AUTOMATED MAIL YOU STUPID!).

**Comment by lehuizi** [comment]
I am running into the same problem every week. Are there some new informations available about the spam headers?

**Comment by MSFTTracyP** [comment]
Hello and thank you for bringing this to light. At the end of my investigation of this issue, I've discovered that the RuleIDs, though they appear in the information that is customer-facing, are not meant to be analysed by customers, and are meant to be internally examined. The best course is to take these RuleIDs to Support for a resolution, here: https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75. Again, apologies for any confusion and frustration this has caused. I've taken actions internally to address this issue. Thank you, again.

**Comment by MatthewDVance** [comment]
Sorry that's a bullshït answer.  Those rule IDs apparently govern how our clients email is or is not delivered properly.  

Please contact the person that decided you shouldn't be transparent and let them know we would like them to stick a fork in a mains outlet. K thx bai

**Comment by patschi** [comment]
+1 @MatthewDVance 

Furthermore, when those rule IDs are internal-only, how should the copy-paste Outlook Sender Support be a help with this at all, when all these details are clearly internal-only?

When I was trying to get more information why my legit mails were classified as junk, I got following useless reply:
```
I do not see anything offhand that would be preventing your mail from reaching our customers. 
 
We Investigate issues based on IP addresses, but not on domain addresses. 
For more detailed information about best sending practices to Outlook.com users,
please review the following white paper:
http://download.microsoft.com/download/e/3/3/e3397e7c-17a6-497d-9693-78f80be272fb/enhance_deliver.pdf
```

Beside that, the white paper has references to Windows Live Hotmail, Exchange/Outlook 2003/2007 and Windows Vista. Doesn't really seem to be up-to-date at all.

To be honest, this sounds more like a occupational therapy than a real solution for anyone. Google/Bing a bit and you may find out many, many complaints about such issues and no one has ever been able to help at all - since years. That has to change, seriously.

**Comment by beuss** [comment]
> The best course is to take these RuleIDs to Support for a resolution, here: https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75

You mean the support whose only answer is "put an unsubscribe link in your mail" when you tell them you're not talking about bulk generated emails but human written ones? Seriously you know that silently undelivered legitimate emails have an impact on business? At least allow them to remove servers from blacklist when they receive a complaint. I've a test live mailbox CCi'ed from all my emails, they all get into junk folder despite thousands of "mark as legit" actions, all being human written, DKIM valid, SPF valid and server IP change. Outlook is the **only** platform not treating them as legit.

**Comment by andryyy** [comment]
![image](https://user-images.githubusercontent.com/2972950/63635271-25cf9800-c661-11e9-9e0f-327f46430a78.png)

See the above IP reputation FROM YOUR OWN SYSTEM. Mail is delivered to "Junk" anyway. I mark it as "non-Junk". Mail is still delivered to "Junk" the next time!

What the hell is wrong with you guys? Why does it not deliver to my Outlook Inbox, when I mark it as NOT Junk?

Sending a mail from another domain, but still the same server: no Junk.

The filtering is totally broken and useless. You cannot keep customers on Outlook like this.
People should really, really move away their customers from Outlook systems, if they want them to receive valid mail.

**Comment by patschi** [comment]
Just to add a fun-fact: Even newsletter (or sort of) mails from Microsoft are classified as junk. Yeah, the junk filter really seems to work as intended.
![image](https://user-images.githubusercontent.com/2029878/63640306-cabc9600-c69e-11e9-89ee-04a0fb456356.png)

If anyone at Microsoft cares about the delivery of their own mails (apparently all mails outside of MS doesn't matter anyway):
```
Subject: The Microsoft Edge Beta is here!
Date: Tue, 20 Aug 2019 10:16:10 -0600
x-job: 7279955_685806
Message-ID: <58ea90c1-3e2c-46a3-84c6-9f3829690970@atl1s07mta667.xt.local>
X-MS-Exchange-Organization-AuthSource:
VE1EUR02FT023.eop-EUR02.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-PublicTrafficType: Email
X-MS-UserLastLogonTime: 8/20/2019 12:11:52 PM
X-MS-Office365-Filtering-Correlation-Id: 2c66e4ee-6cab-4eed-32b1-08d72589b803
X-Microsoft-Antispam:
BCL:7;PCL:0;RULEID:(2390118)(5000188)(711020)(4605104)(610169)(650170)(651021)(8291501072);SRVR:VE1EUR02HT110;
X-MS-TrafficTypeDiagnostic: VE1EUR02HT110:
X-SID-PRA: EMAIL@ENGAGE.WINDOWS.COM
X-SID-Result: PASS
X-MS-Exchange-Organization-SCL: 6
X-MS-Exchange-Organization-PCL: 2
X-MS-Exchange-AtpMessageProperties: SA|SL
X-OriginatorOrg: outlook.com
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 20 Aug 2019 16:16:11.9485
(UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 2c66e4ee-6cab-4eed-32b1-08d72589b803
X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-Microsoft-Antispam-Mailbox-Delivery:
abwl:0;wl:0;pcwl:0;kl:0;iwl:0;dwl:0;dkl:0;rwl:0;ucf:0;jmr:0;ex:0;auth:1;dest:J;OFR:SpamFilterAuthJ;ENG:(5062000261)(5061607266)(5061608174)(4900115)(4920090)(6350004)(4950130)(4990090)(9140004);RF:JunkEmail;
X-Message-Info:
qoGN4b5S4yrvY9F+ALPOw5XHuHZ645Ma6z1iTnOkp3OOzx7gkkgGpRjBRpIEf+8zYqdwByAAi+dqDr+s/ELGa5PVisQrBnXSiZ+5u+ct1drBCikR4RsdQ3WdOViJ/6M5dm4Mgy0ra0D3LHj9mwtisbg3t7yrrpJcLWxifeg7Zp2+zTIJGRfXdpTrAqc6P+bOLYhsbihy+5NvMsG6psjX/A==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0wO0Q9MjtHRD0yO1NDTD02
X-Microsoft-Antispam-Message-Info:
R+T6azVxVYIYoZp+rp5TbFtJre4irrxAhch/aUchWJRhxzLNXcuj0ESOjBa7A6fVq+0Wju+9Y2/Newi6Oq1tgRmneADveWaX6blo6Dv8Hrt3IznP43HdTkEhUdQBmy3JDgpqp7pHytvhzL0Fh+esthyOphpdIpYkOZZlRks1SynFQr8kq46mFzWt+kwHhdnrE4MRXunqoM4OPJRepBgJOQXPs0niWAT96qFSx/hGJG7HFf1MYwxPY5s7F7/obYcwp4kv1v/Oco/m35C0VDxSHe+5i/1S24jf0VqVDwRD+RKxeXLx44nixH+Lup3HgdOIJRnQVXilkhgNmgYNeMBGfgPQcSLzmj2ldrDNrBLDYHcFGx2Wm3vALs6PmaOqDzH5LtbYW93Fo5oKbGbDZMWmdv7VbmSw70cOw/dnBjCT1S8mfpiJCC3L25S63XrY3vi2QpU2838qHYtcCzv3PAD6YdPYrTZFF6qRBcGnD02R4Kp+sfBoig0C1cE58RrBMRx+hi5XGwT9z4pdhVE0fsULBEWME/ieOh+7ZOPQWno7oz4DkBETp9ol54DP60NciuiNXXdW8hh5CoMDyycIdKGdgBS4T6r5jjv6RZtKP40o3yrgsk4wQ11BmPc3IwP8ji24aEvlXjFGnWUaPVhPeE4Zm0PlYP7lxxNDmVND/Qw1ewwwUfBOZhfpEeXK1PsMTNGwFlgXxjbPJgZsZk5KulNF9/Mm2OYeQuCK1dUlo56S0x7mCk7zIMQqr59uBhFv17YyqjWiEywaXxcbaCgw3ufhEZdMkLLEI7ZhY+BTOJfx8ZckEDwqTvReIe/Nl9/FxWHKeb7CleqGVgleT1CiX9zdkusve95WALodAKKXEb4tKjzx/d/R3749VWsOwOAtON7kr/XH0hlHmssqWTbkK+wBf5OS6Yh85zzecIlc1IzZNjwq0zNVM/iRADdM8HQjvbAW
```

The [`Bulk Complaint Level`](https://docs.microsoft.com/en-us/office365/SecurityCompliance/anti-spam-message-headers) is `7`.

**Comment by beuss** [comment]
And more fun facts, without any configuration changes nor IP status changes, some emails are delivered into INBOX… headers show the same RULEIDs as the ones flagged as junk

**Comment by dstrome** [comment]
@MatthewDVance, your response is inappropriate and violates the Code of Conduct and, as such, has been removed. Further inappropriate responses may result in your account being banned from future participation in any repo on docs.microsoft.com

This conversation is now locked.
